config/routes.rb
Siesta::Application.routes.draw do

  # Student controllers
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resource :profile, :only => [ :show, :edit, :update ]
  resources :schoolings
  resources :user_documents
  resources :user_requests
  resources :remote_users, :only => [ :index ]
  resources :disabilities, :only => [ :index ]
  # Default controllers
  root :to => "profiles#show"

  # Academic controllers
  namespace :academics do 
    # resources :events
    resources :student_requests, :only => [:index] do
      get :approve, :on => :member
      get :reject, :on => :member
    end
    #resources :calendars
    #resources :office_cubicles do
    #  resources :calendars
    #end
    root :to => "student_requests#index"
    devise_for :users, :only => :sessions, :format => false
  end

  # Admin controllers
  namespace :managers do
    resources :students do
      get :card_back, :on => :member
      get :card_front, :on => :member
      get :authorize, :on => :member
      get :destroy_request, :on => :member
      get :search, :on => :collection
    end
    resources :photos
    resources :emails
    resources :periods
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end

  namespace :librarians do
    resources :students 
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end
  
  namespace :public do
    resources :students
  end

  devise_for :accounts, :controllers => { :sessions => "accounts/sessions",
                                          :passwords => "accounts/passwords",
                                          :registrations => "accounts/registrations" }
end

app/models/notifier.rb
# encoding: utf-8
class Notifier < ActionMailer::Base
  include ApplicationHelper

  default :from => "no-reply-siesta@fisica.unam.mx"
  $subject_prefix = '[SIESTA] - '

  def new_password(user)
    send_mail_to(user, "Nueva contraseña")
  end

  def new_user(user)
    send_mail_to(user, "Información de nueva cuenta")
  end

  def student_notification(user)
    send_mail_to(user, "Su solicitud de Estudiante Asociado fue enviada")
  end

  def academic_notification(user_request)
    @user_request = user_request
    mail(:to => @user_request.user_incharge.email, :subject => $subject_prefix + 'Solicitud de Estudiante Asociado - IFUNAM') do |format|
      format.text
    end
  end

  def authorized_notification(user_request)
    subject = 'Solicitud de Estudiante Asociado autorizada'
    @user_request = user_request
    filename = 'ReglasOperacionEstudiantesAsociadosIFUNAMAgosto2010.pdf'
    mail(:to => @user_request.user.email, :subject => $subject_prefix + subject) do |format|
      format.text
      attachments[filename] = File.read(Rails.root.to_s + "/app/views/notifier/#{filename}")  
    end
  end
  
  def authorized_notification_academic(user_request)
    subject = 'Solicitud de Estudiante Asociado autorizada'
    @user_request = user_request
    filename = 'ReglasOperacionEstudiantesAsociadosIFUNAMAgosto2010.pdf'
    mail(:to => @user_request.user_incharge.email, :subject => $subject_prefix + subject) do |format|
      format.text
      attachments[filename] = File.read(Rails.root.to_s + "/app/views/notifier/#{filename}")  
    end
  end

  def authorized_notification_academic_coordination(user_request)
    subject = 'Solicitud de autorización de Estudiante Asociado'
    @user_request = user_request
    mail(:to => 'cd-if@fisica.unam.mx', :subject => $subject_prefix + subject) do |format|
      format.text
    end
  end

  def authorization_from_academic_coordination_to_student(user_request)
    subject = 'Solicitud autorizada por la Coordinación Docente'
    @user_request = user_request
    mail(:to => @user_request.user.email, :subject => $subject_prefix + subject) do |format|
      format.text
    end
  end

  def authorization_from_academic_coordination_to_academic(user_request)
    subject = 'Solicitud autorizada por la Coordinación Docente'
    @user_request = user_request
    mail(:to => @user_request.user_incharge.email, :subject => $subject_prefix + subject) do |format|
      format.text
    end
  end


  def unauthorized_notification(user)
    subject = 'Solicitud de Estudiante Asociado no autorizada'
    @user = user
    mail(:to => user.email, :subject => $subject_prefix + subject) do |format|
      format.text
    end
  end

  def unauthorized_notification_academic(user, user_incharge)
    subject = 'Solicitud de Estudiante Asociado no autorizada'
    @user = user
    mail(:to => user_incharge.email, :subject => $subject_prefix + subject) do |format|
      format.text
    end
  end

  def office_cubicle_notification(event)
    subject = 'Notificación de asignación de Oficina o cubículo'
    @event  = event
    mail(:to => @event.user_request.user.email,:cc => @event.user_request.user_incharge.email, :subject => $subject_prefix + subject) do |format|
      format.text
    end
  end

  def new_ldap_user(user_profile)
    @user_profile = user_profile
    mail(:to => 'vic@fisica.unam.mx', :subject => $subject_prefix + 'Nueva cuenta de Estudiante Asociado - IFUNAM') do |format|
        format.text
    end
  end

  private
  def send_mail_to(user, subject)
    @user = user 
    mail(:to => user.email, :subject => $subject_prefix + subject) do |format|
      format.text
    end
  end
end

app/views/notifier/academic_notification.text.erb
********************************************************************
*                      Este es un reporte automático               *
*                            NO HAGA REPLY                         *
********************************************************************

Estimado Académico del IFUNAM, usted ha recibido una solicitud para 
asociar un estudiante al Instituto de Física.

Estudiante: <%= @user_request.user.person.fullname %>
Periodo: <%= @user_request.period.name %>
Actividad a realizar:  <%= @user_request.role.name %>
Tipo de solicitud: <%= @user_request.is_restamped == true ? 'Resello' : 'Solicitud nueva' %>

Para atender esta solicitud debe usar la siguiente dirección:

https://siesta.fisica.unam.mx/academics/

NOTA: Los usuarios de Internet Explorer deben copiar y pegar la liga en su navegador
en caso de que el sistema no se abra automáticamente. Esto se debe a un problema
de compatibilidad entre el servidor web y su navegador.

<% if @user_request.want_office_cubicle %>
El estudiante también ha solicitado asignación de un espacio en los cubículos de estudiantes,
por favor realizé esta asignación después de haber autorizado la solicitud de estudiante
asociado.

<% end %>
Recuerde que, de acuerdo a las reglas de operación para tener estudiantes
asociados, también debe notificar a la Coordinación Docente cuando termine
su relación con este estudiante.

Gracias por usar el SIESTA.

== NOTA ==
Esta aplicación es compatible con las versiones más recientes de los
navegadores: Firefox, Internet Explorer, Safari o Chrome.


Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
====================================================================

app/views/notifier/authorization_from_academic_coordination_to_academic.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

Se le notifica que la Coordinación docente ha autorizado la siguiente 
solicitud de estudiante asociado:

Estudiante: <%= @user_request.user.person.fullname %>
Académico: <%= @user_request.user_incharge.fullname %>
Periodo: <%= @user_request.period.name %>
Actividad a realizar:  <%= @user_request.role.name %>
Tipo de solicitud: <%= @user_request.is_restamped == true ? 'Resello' : 'Solicitud nueva' %>

El trámite de esta solicitud ha concluído.

Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************

app/views/notifier/authorization_from_academic_coordination_to_student.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

Su solicitud de estudiante asociado ha sido *autorizada* por la 
Coordinación Docente.

<% if @user_request.is_restamped %>
Su cuenta correo electrónico y el servicio  de biblioteca para el periodo 
<%= @user_request.period.name %> han sido activados. 

No es necesario que se presente  a la oficina de la Coordinación 
Docente, a menos que necesite imprimir de nuevo su credencial.

El trámite de esta solicitud ha concluído.
<% else %>
Para concluir este trámite y ser oficialmente estudiante asociado al 
Instituto de Física, debe presentarse en la oficina de la Coordinación 
Docente para poder elaborar su credencial, dar de alta su cuenta de correo 
electrónico (la cual deberá usar al menos para recibir notificaciones de
esta Coordinación) y llenar el formato para la tarjeta de ingreso al 
instituto. De lo contrario, se le puede negar la entrada al mismo.
<% end %>

Cuando concluya su trabajo de investigación en el instituto, debe notificar 
a esta Coordinación al respecto.

Gracias por usar  el Sistema de Estudiantes Asociados - SIESTA.

Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************

app/views/notifier/authorized_notification.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

Su solicitud de estudiante asociado ha sido *autorizada* por el
académico responsable.

<% if @user_request.is_restamped %>
Para concluir el trámite de resello, la Coordinación Docente 
enviará una notificación a su correo electrónico en el Instituto de 
Física donde indicará que su correo electrónico y el servicio 
de biblioteca para el periodo <%= @user_request.period.name %> ha sido 
activado. 

No es necesario que se presente  a la oficina de la Coordinación 
Docente, a menos que necesite imprimir de nuevo su credencial.

<% else %>
Para concluir este trámite y ser oficialmente estudiante asociado al 
Instituto de Física, debe presentarse en la oficina de la Coordinación 
Docente para poder elaborar su credencial, dar de alta su cuenta de correo 
electrónico (la cual deberá usar al menos para recibir notificaciones de
esta Coordinación) y llenar el formato para la tarjeta de ingreso al 
instituto. De lo contrario, se le puede negar la entrada al mismo.
<% end %>

Cuando concluya su trabajo de investigación en el instituto, debe notificar 
a esta Coordinación al respecto.

Gracias por usar  el Sistema de Estudiantes Asociados - SIESTA.

Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************

app/views/notifier/authorized_notification_academic.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

La solicitud de estudiante asociado ha sido *autorizada*.

Estudiante: <%= @user.person.fullname %>

Para concluir este trámite y ser oficialmente estudiante asociado al 
Instituto de Física, el estudiante debe presentarse en la oficina de la 
Coordinación Docente para poder elaborar su credencial, dar de alta su 
cuenta de correo electrónico (la cual deberá usar al menos para recibir 
notificaciones de esta Coordinación) y llenar el formato para la tarjeta
de ingreso al instituto. De lo contrario, se le puede negar la entrada 
al mismo.

Cuando el estudiante concluya su trabajo de investigación en el instituto,
debe notificar  esta Coordinación al respecto.

Gracias por usar  el Sistema de Estudiantes Asociados - SIESTA.

Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************

app/views/notifier/authorized_notification_academic_coordination.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

La siguiente solicitud de estudiante asociado ha sido *autorizada* por
el académico del Instituto de Física.

Estudiante: <%= @user_request.user.person.fullname %>
Académico: <%= @user_request.user_incharge.fullname %>
Periodo: <%= @user_request.period.name %>
Actividad a realizar:  <%= @user_request.role.name %>
Tipo de solicitud: <%= @user_request.is_restamped == true ? 'Resello' : 'Solicitud nueva' %>

Para autorizar esta solicitud debe usar la siguiente liga:

https://siesta.fisica.unam.mx<%= managers_student_path(@user_request.user) %>

Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************

app/views/notifier/new_ldap_user.text.erb
********************************************************************
*                      Este es un reporte automático               *
*                            NO HAGA REPLY                         *
********************************************************************

Estimad@ administrador@ de sistemas,

Le notificamos que se ha creado una cuenta en el servidor de LDAP
desde el Sistema de Estudiantes Asociados al Instituto de Física:

  Usuario: <%= @user_profile.login %>
  Nombre completo: <%= @user_profile.fullname %>
  Grupo: <%= @user_profile.group %>
  Periodo: <%= @user_profile.period %>


Gracias por usar el Sistema de Estudiantes Asociados - SIESTA.


Instituto de Física
Universidad Nacional Autónoma de México
====================================================================

app/views/notifier/new_password.text.erb
********************************************************************
*                      Este es un reporte automático               *
*                            NO HAGA REPLY                         *
********************************************************************

La nueva contraseña para su cuenta '<%= @user.login %>' es:

<%= @user.random_password %>

Para entrar al sistema use el siguiente enlace:

<%= new_session_url(:host => 'siesta.fisica.unam.mx') %>

Gracias por usar el Sistema de Estudiantes Asociados - SIESTA.

Instituto de Física
Universidad Nacional Autónoma de México
====================================================================

app/views/notifier/new_user.text.erb
********************************************************************
*                      Este es un reporte automático               *
*                            NO HAGA REPLY                         *
********************************************************************

Su cuenta en el sistema de Estudiantes Asociados del Instituto de
Física ha sido <<creada>>:

  Usuario: <%= @user.login %>
  Contraseña: ***********

Para entrar al sistema es necesario que confirme la activación de
su cuenta usando el siguiente enlace en el navegador de su
preferencia:

<%= new_session_url(:host => 'siesta.fisica.unam.mx') %>

Una vez aceptada su solicitud por el académico responsable, le llegará 
un correo electrónico con las instrucciones para finalizar su asociación 
al instituto como estudiante.

Gracias por usar el Sistema de Estudiantes Asociados - SIESTA.

Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
====================================================================

app/views/notifier/office_cubicle_notification.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

Se le notifica que se ha realizado la siguiente la asignación de
cubículo/oficina para el perido <%= @event.user_request.period.name %>:

Estudiante: <%= @event.user_request.user.person.fullname %>
Académico: <%= @event.user_request.user_incharge.fullname %>
Actividad a realizar:  <%= @event.user_request.role.name %>
Tipo de solicitud: <%= @event.user_request.is_restamped == true ? 'Resello' : 'Solicitud nueva' %>
Oficina o Cubículo: <%= @event.office_cubicle.as_text %>

Fecha de inicio:  <%= @event.start_date %>
Fecha de término: <%= @event.end_date %>

== Horarios ==
<%- @event.event_days.each do |event_day| %>
    <%= "Día: #{event_day.day}" %>
    <%= "Hora de inicio: #{event_day.start_time}" %>
    <%= "Hora de término: #{event_day.end_time}" %>

<% end %>
Coordinación Docente, Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************

app/views/notifier/student_notification.text.erb
********************************************************************
*                      Este es un reporte automático               *
*                            NO HAGA REPLY                         *
********************************************************************

Su solicitud de estudiante asociado al Instituto de Física ha sido
enviada. En fecha próxima recibirá la aprobación de su responsable 
académico.

Gracias por usar el SIESTA.

Instituto de Física
Universidad Nacional Autónoma de México
====================================================================

app/views/notifier/unauthorized_notification.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

Su solicitud de estudiante NO fue *autorizada* por su responsable 
académico.

Gracias por usar  el Sistema de Estudiantes Asociados - SIESTA.

Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************

app/views/notifier/unauthorized_notification_academic.text.erb
**********************************************************************
*              Este es un mensaje generado automáticamente           *
*                          NO HAGA REPLY                             *
**********************************************************************

La solicitud de estudiante NO fue *autorizada*

Estudiante: <%= @user.person.fullname %>

Gracias por usar  el Sistema de Estudiantes Asociados - SIESTA.

Instituto de Física
Universidad Nacional Autónoma de México
**********************************************************************