config/routes.rb
Siesta::Application.routes.draw do

  # Student controllers
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resource :profile, :only => [ :show, :edit, :update ]
  resources :schoolings
  resources :user_documents
  resources :user_requests
  resources :remote_users, :only => [ :index ]
  resources :disabilities, :only => [ :index ]
  # Default controllers
  root :to => "profiles#show"

  # Academic controllers
  namespace :academics do 
    # resources :events
    resources :student_requests, :only => [:index] do
      get :approve, :on => :member
      get :reject, :on => :member
    end
    #resources :calendars
    #resources :office_cubicles do
    #  resources :calendars
    #end
    root :to => "student_requests#index"
    devise_for :users, :only => :sessions, :format => false
  end

  # Admin controllers
  namespace :managers do
    resources :students do
      get :card_back, :on => :member
      get :card_front, :on => :member
      get :authorize, :on => :member
      get :destroy_request, :on => :member
      get :search, :on => :collection
    end
    resources :photos
    resources :emails
    resources :periods
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end

  namespace :librarians do
    resources :students 
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end
  
  namespace :public do
    resources :students
  end

  devise_for :accounts, :controllers => { :sessions => "accounts/sessions",
                                          :passwords => "accounts/passwords",
                                          :registrations => "accounts/registrations" }
end

app/models/schooling.rb
class Schooling < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_size :file, :less_than => 10.megabytes
  validates_attachment_content_type :file, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'application/postscript', 'application/x-pdf']

  attr_accessible :degree_id, :career, :school, :institution, :studentid, :average, :credits, :startyear, :endyear, :is_studying_this, :is_titleholder, :file

  validates_presence_of :degree_id, :career, :school, :institution, :average, :credits, :startyear
  validates_numericality_of :id, :allow_nil => true, :greater_than => 0, :only_integer => true
  validates_numericality_of :average #, :greater_than => 5.9, :less_than_or_equal_to => 10
  validates_numericality_of :credits #,  :greater_than => 0, :less_than_or_equal_to => 100, :only_integer => true
  validates_numericality_of :startyear, :greater_than => (Date.today.year.to_i - 50), :less_than_or_equal_to => Date.today.year.to_i, :only_integer => true
  validates_numericality_of :endyear, :greater_than => (Date.today.year.to_i - 50), :only_integer => true, :allow_nil => true

  belongs_to :user
  belongs_to :degree

  default_scope order("startyear DESC, degree_id DESC, career ASC")
end

app/controllers/schoolings_controller.rb
class SchoolingsController < UserResourcesController
end

app/views/schoolings/_form.html.haml
= render :partial => 'shared/errors', :locals => { :f => f}

%b=t '.degree_and_school'
= f.association :degree, :required => true, :input_html => { :class => 'chzn-select' }
= f.input :career, :required => true, :as => :string, :input_html => { :class => 'input-medium' }
= f.input :school, :required => true, :as => :string, :input_html => { :class => 'input-medium' }
= f.input :institution, :required => true, :as => :string, :input_html => { :class => 'input-medium' }

%hr/
%b= t '.degree_details'
= f.input :studentid, :as => :string, :input_html => { :class => 'input-small' }
= f.input :average, :as => :string, :input_html => { :class => 'input-small' }
= f.input :credits, :as => :string, :input_html => { :class => 'input-small' }
= f.input :startyear, :required => true, :as => :string, :input_html => { :class => 'input-small' }
= f.input :endyear, :required => true, :as => :string, :input_html => { :class => 'input-small' }

%hr/
%b= t '.degree_status'
%div.control-group.string.required
  = label :is_studying_this, t(:is_studying_this, :scope => 'activerecord.attributes.schooling'), :class => 'string required control-label'
  %div.controls
    = (f.radio_button :is_studying_this, true, :checked => (f.object.is_studying_this unless f.object.nil?)) + 'Sí'
    = (f.radio_button :is_studying_this, false, :checked => (!f.object.is_studying_this unless f.object.nil?)) + 'No'
%div.control-group.string.required
  = label :is_title_holder, t(:is_titleholder, :scope => 'activerecord.attributes.schooling'), :class => 'string required control-label'
  %div.controls
    = (f.radio_button :is_titleholder, true, :checked => (f.object.is_titleholder unless f.object.nil?)) + 'Sí'
    = (f.radio_button :is_titleholder, false, :checked => (!f.object.is_titleholder unless f.object.nil?)) + 'No'

%hr/
%b= t '.degree_docs'
= f.input :file, :required => true, :as => :file

.span12
  = f.button :submit, :class => 'btn btn-success'
  = link_to t(:cancel), schoolings_path, :class => 'btn'

app/views/schoolings/_schooling.html.haml
%tr
  %td
    = schooling.degree.name
  %td
    %p
      = t(:career, :scope => 'activerecord.attributes.schooling') + ': '
      = schooling.career
    %p 
      = t(:school, :scope => 'activerecord.attributes.schooling') + ': '
      = schooling.school
    %p
      = t(:institution, :scope => 'activerecord.attributes.schooling') + ': '
      = schooling.institution
    %p 
      = t(:average, :scope => 'activerecord.attributes.schooling') + ': '
      = schooling.average
      = ', '
      = t(:credits, :scope => 'activerecord.attributes.schooling') + ': '
      = schooling.credits || '-'
    %p 
      = t(:is_studying_this, :scope => 'activerecord.attributes.schooling') + ': '
      = schooling.is_studying_this? ? 'Sí' : 'No'
    %p 
      = t(:is_titleholder, :scope => 'activerecord.attributes.schooling') + ': '
      = schooling.is_titleholder? ? 'Sí' : 'No'
    %p
      = link_to t(:cardex), schooling.file.url, :target => :new
  %td
    = schooling.startyear
  %td
    = schooling.endyear
  %td.btn-group
    = link_to t(:edit), edit_schooling_path(schooling), :class => 'btn btn-info'
    = link_to t(:delete), schooling_path(schooling), :method => :delete, :confirm => t(:confirm_question), :class => 'btn btn-warning'

app/views/schoolings/_schooling_show.html.haml
= show_for schooling_show do  |record|
  = record.association :degree
  = record.attribute :career
  = record.attribute :school
  = record.attribute :institution
  = record.attribute :studentid
  = record.attribute :average
  = record.attribute :credits
  = record.attribute :startyear
  = record.attribute :endyear
  = record.attribute :is_studying_this
  = record.attribute :is_titleholder
- unless schooling_show.file.nil?
  %p= link_to t(:cardex), schooling_show.file.url, :target => :new

app/views/schoolings/edit.html.haml
%h3= t '.title'
= simple_form_for(@schooling, :html => { :multipart => true }) do |f|
  = render :partial => 'form', :locals => { :f => f }

app/views/schoolings/index.html.haml
%h3= I18n.t 'schoolings.index.title'

%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th= t(".degree")
      %th= t(".description")
      %th= t(".startyear")
      %th= t(".endyear")
      %th= t(:actions)
  %tbody
    = render :partial => @schoolings

.span12
  = link_to t(:new), new_schooling_path, :class => 'btn btn-primary'

app/views/schoolings/new.html.haml
%h3= t '.title'
= simple_form_for(@schooling, :html => { :multipart => true }) do |f|
  = render :partial => 'form', :locals => { :f => f}

app/views/schoolings/show.html.haml
%h3=t '.title'
= render :partial => 'schooling_show', :object => @schooling
.span12
  = link_to t(:edit), edit_schooling_path, :class => 'btn btn-primary'
  = link_to t(:back), schoolings_path, :class => 'btn'

app/views/schoolings/unauthorized.html.haml
= render 'shared/unauthorized'

.span12
  = link_to t(:back), schoolings_path, :class => 'btn btn-success'