config/routes.rb
Siesta::Application.routes.draw do

  # Student controllers
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resource :profile, :only => [ :show, :edit, :update ]
  resources :schoolings
  resources :user_documents
  resources :user_requests
  resources :remote_users, :only => [ :index ]
  resources :disabilities, :only => [ :index ]
  # Default controllers
  root :to => "profiles#show"

  # Academic controllers
  namespace :academics do 
    # resources :events
    resources :student_requests, :only => [:index] do
      get :approve, :on => :member
      get :reject, :on => :member
    end
    #resources :calendars
    #resources :office_cubicles do
    #  resources :calendars
    #end
    root :to => "student_requests#index"
    devise_for :users, :only => :sessions, :format => false
  end

  # Admin controllers
  namespace :managers do
    resources :students do
      get :card_back, :on => :member
      get :card_front, :on => :member
      get :authorize, :on => :member
      get :destroy_request, :on => :member
      get :search, :on => :collection
    end
    resources :photos
    resources :emails
    resources :periods
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end

  namespace :librarians do
    resources :students 
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end
  
  namespace :public do
    resources :students
  end

  devise_for :accounts, :controllers => { :sessions => "accounts/sessions",
                                          :passwords => "accounts/passwords",
                                          :registrations => "accounts/registrations" }
end

app/views/recover_passwords/new.html.haml
- blueprint 'span-15 prepend-2 last' do
  %h3= 'Enviar contraseña nueva'
  - form_for(@user, :recover_password, :url => recover_password_path) do |f|
    %p
      = f.label 'Correo electrónico con el que registro su cuenta'
    %p
      = f.text_field :email, :size => 30
    - blueprint 'span-15 last', :id => 'buttons' do
      = f.submit 'Enviar contraseña', :class => 'ui-state-default ui-corner-all button'
      = link_to 'Cancelar', new_session_path, :class => 'ui-state-default ui-corner-all button'

app/views/recover_passwords/show.html.haml
%div{:class => 'span-19 prepend-5', :style => 'text-align: center;'}
  %div{:class => "message_box blue", :style => 'padding: 20px; text-align: center;'}
    %h3="La contraseña de su cuenta #{@user.login} se ha generado!"
    %p
      ="Se ha enviado correo electrónico a "
      %b= @user.email
      =", en el mensaje encontrará las instrucciones para entrar al sistema."
  %br
  %div{:class => "notice_box red"}
    %p 
      ="Sí el mensage no aparece en su buzón de correo electrónico revise en la carpeta de "
      %b= "spam o junk."
  %br
  %p{:style=>'color: #006666; font-size: 15px; text-align: left;', :id => 'buttons'}
    = "Gracias por usar el SIESTA!"
    %br 
    %br 
    = link_to 'Regresar', new_session_path, :class => 'ui-state-default ui-corner-all button'