config/routes.rb
Siesta::Application.routes.draw do

  # Student controllers
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resource :profile, :only => [ :show, :edit, :update ]
  resources :schoolings
  resources :user_documents
  resources :user_requests
  resources :remote_users, :only => [ :index ]
  resources :disabilities, :only => [ :index ]
  # Default controllers
  root :to => "profiles#show"

  # Academic controllers
  namespace :academics do 
    # resources :events
    resources :student_requests, :only => [:index] do
      get :approve, :on => :member
      get :reject, :on => :member
    end
    #resources :calendars
    #resources :office_cubicles do
    #  resources :calendars
    #end
    root :to => "student_requests#index"
    devise_for :users, :only => :sessions, :format => false
  end

  # Admin controllers
  namespace :managers do
    resources :students do
      get :card_back, :on => :member
      get :card_front, :on => :member
      get :authorize, :on => :member
      get :destroy_request, :on => :member
      get :search, :on => :collection
    end
    resources :photos
    resources :emails
    resources :periods
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end

  namespace :librarians do
    resources :students 
    root :to => "students#index"
    devise_for :users, :only => :sessions, :format => false
  end
  
  namespace :public do
    resources :students
  end

  devise_for :accounts, :controllers => { :sessions => "accounts/sessions",
                                          :passwords => "accounts/passwords",
                                          :registrations => "accounts/registrations" }
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  set_table_name 'users'
  devise :ldap_authenticatable
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :name, :startdate, :enddate, :is_active
  validates_numericality_of :id, :allow_nil => true, :only_integer => true, :greater_than => 0
  validates_presence_of :name, :startdate, :enddate
  validates_inclusion_of :is_active, :in=> [true, false]
  validates_uniqueness_of :name

  default_scope :order => 'startdate DESC, enddate DESC'

  scope :activated, where(:is_active => true).first

  def validate!
   if startdate && enddate
      errors.add("startdate", "must be after checkout") if time_at_midnight(startdate) >= time_at_midnight(enddate)
    end
  end

  def self.most_recent
    Period.activated || Period.last_started
  end

  def self.last_started
    self.order("startdate DESC").limit(1).first
  end

  def self.activated
    self.where(:is_active=>true).first
  end

  def self.previous
    self.where(['startdate < ?', Period.most_recent.startdate]).order('startdate DESC').limit(1).first
  end

  def status
    is_active ? 'Vigente' : 'Desactivado'
  end

  def expired?
    self.enddate < Date.today
  end
  
  private
  def time_at_midnight(date)
    date.to_date
  end
end

app/controllers/managers/application_controller.rb
class Managers::ApplicationController < ActionController::Base
  layout 'admin'
  protect_from_forgery
  before_filter :authenticate_managers_user!
  # The current_user method is required by CanCan gem
  alias_method :current_user, :current_managers_user
  authorize_resource :class => false
end

app/controllers/managers/emails_controller.rb
class Managers::EmailsController < Managers::ApplicationController
 skip_before_filter :verify_authenticity_token, :only => [:update]
 def new
   @student = StudentProfile.find(params[:id])
   @user = LDAP::User.new
 end

 def create
   @user = LDAP::User.new(params[:user])
   @student = StudentProfile.find(params[:student][:id])
   if @user.save
       @student.update_attributes(:email =>params[:user][:login] + '@fisica.unam.mx', :login => params[:user][:login])
       Notifier.new_ldap_user(@student).deliver
     redirect_to managers_email_path(@student)
   else
     render :action => :new
   end
 end

 def show
   @student = StudentProfile.find(params[:id])
   @users = []
   @student.fullname.split(' ').each do |name|
    @users += LDAP::User.all_by_fullname_likes(name.strip)
   end
 end

 def update
    @user = User.find(params[:id])
    @user.email = params[:email]
    @user.login = params[:email].split('@').first
    if @user.save
      redirect_to managers_email_path(@user)
    else
      redirect_to managers_email_path(@user)
    end
 end
end

app/controllers/managers/periods_controller.rb
class Managers::PeriodsController < Managers::ApplicationController
  respond_to :html
  
  def index
    respond_with(@periods = Period.paginate(:page => params[:page] || 1, :per_page =>  params[:per_page] || 10))
  end

  def new
    respond_with(@period = Period.new)
  end
  
  def create
    respond_with(@period = Period.create(params[:period]), :status => :created, :location => managers_periods_path)
  end

  def edit
    respond_with(@period = Period.find(params[:id]))
  end
  
  def update
    @period = Period.find(params[:id])
    respond_with(@period.update_attributes(params[:period]), :status => :updated, :location => managers_periods_path)
  end

  def destroy
    @period = Period.find(params[:id])
    @period.destroy
    respond_with(@period, :status => :deleted, :location => managers_periods_path)
  end
end

app/controllers/managers/photos_controller.rb
class Managers::PhotosController < Managers::ApplicationController
  respond_to :html
  def edit
    respond_with(@person =  Person.find(params[:id]))
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      respond_with(@person, :status => :updated, :location => managers_student_path(:id => @person.user_id))
    else
      respond_with(@person, :status => :unprocessable_entity, :location => edit_managers_photo_path(:id => @person.user_id))
    end
  end
end

app/controllers/managers/sessions_controller.rb
class Managers::SessionsController < Devise::SessionsController
  skip_before_filter :authenticate_user!, :only => [:create, :new]
  def create
    resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    unless Period.activated.nil? 
    	respond_with resource, :location => after_sign_in_path_for(:managers_user)
    else
	respond_with resource, :location => managers_periods_path
    end
  end
end

app/controllers/managers/students_controller.rb
# encoding: utf-8
require Rails.root.to_s + '/lib/reporter'
class Managers::StudentsController < Managers::ApplicationController
  include ApplicationHelper
  respond_to :html, :js, :csv, :xls

  def index
    respond_with(@users = User.student.fullname_asc.paginated_search(params))
  end

  def search
    respond_with(@users = StudentProfile.student.fullname_asc.simple_search(params)) do |format|
      format.js
      format.csv do
        headers["Content-Type"] = 'text/csv'
        headers['Content-Disposition'] = "attachment; filename=\"search_report_#{Time.now.strftime("%Y%m%d%H%m")}.csv\""
        render :action => 'search.csv', :layout => false
      end
      format.xls do
        @report = Siesta::Reporter.new(@users, params[:search])
        @report.build
        send_file(@report.file_path, :type => "application/vnd.ms-excel", :disposition => 'attachment')
      end
    end
  end

  def show
    @student = StudentProfile.find(params[:id])
    @student.person.build_card_image
    respond_with(@student)
  end

  def card_front
    @card = Card.new(params[:id])
    respond_to do |format|
      format.jpg do
        send_data @card.front, :filename => "front_studentid.jpg", :type => 'image/jpeg', :disposition => 'attachment'  
      end
    end
  end

  def card_back
    @card = Card.new(params[:id])
    respond_to do |format|
      format.jpg do
        send_data @card.back, :filename => "back_studentid.jpg", :type => 'image/jpeg', :disposition => 'attachment'  
      end
    end
  end

  def authorize
    @user_request = UserRequest.find(params[:id])
    @user_request.update_attribute(:is_official,true)
    respond_with(@user_request)
  end

  def destroy_request
    @user_request = UserRequest.find(params[:id])
    @user_request.destroy
    render :nothing => true
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with(@user, :status => :deleted, :location => managers_users_path)
  end
end

app/views/managers/periods/_form.html.haml
.well.span10.offset1
  = render :partial => 'shared/errors', :locals => { :f => f }
  = f.input :name, :as => :string, :required => 'true', :input_html => { :class => 'input-medium' }
  = f.input :startdate, :as => :string, :required => 'true', :input_html => { :class => 'input-medium date' }
  = f.input :enddate, :as => :string, :required => 'true', :input_html => { :class => 'input-medium date' }

  %div.control-group.string.required
    = label :status, t(:status, :scope => 'activerecord.attributes.period'), :class => 'string required control-label'
    %div.controls
      = (f.radio_button :is_active, false, :checked => (!f.object.is_active unless f.object.nil?)) + 'Inactivo'
      = (f.radio_button :is_active, true, :checked => (f.object.is_active unless f.object.nil?)) + 'Vigente'

  %p
    = f.button :submit, t(:save), :class => 'btn btn-success'
    = ' '
    = link_to 'Cancelar', managers_periods_path, :class => 'btn'

app/views/managers/periods/_record.html.haml
%tr
  %td= record.name
  %td= record.startdate
  %td= record.enddate
  %td= record.status
  %td
    = link_to t(:edit), edit_managers_period_path(record), :class => 'btn btn-info'
    = link_to t(:delete), managers_period_path(record), :method => :destroy, :class => 'btn btn-danger', :confirm => t(:confirm_question)

app/views/managers/periods/edit.html.haml
%h3= 'Modificar periodo'
= simple_form_for @period,  :url => managers_period_path(@period) do |f|
  = render :partial => 'form', :locals => { :f => f}

app/views/managers/periods/index.html.haml
%h3= 'Periodos'

%table.table.table-bordered
  %thead
    %tr
      %th= 'Periodo'
      %th= 'Fecha de inicio del resello'
      %th= 'Fecha de término del resello'
      %th= 'Estado'
      %th= 'Acciones'

  %tbody{:id => :collection}
    = render :partial => 'record', :collection => @periods

#paginator.span12
  = will_paginate(@periods)

.span11.offset1
  = link_to 'Agregar nuevo periodo', new_managers_period_path, :class => 'btn btn-primary'

app/views/managers/periods/new.html.haml
%h3= 'Nuevo periodo'
= simple_form_for @period, :url => managers_periods_path do |f|
  = render :partial => 'form', :locals => { :f => f}